---
- name: Create a Job Template with no survey
  ansible.controller.job_template:
    name: '{{ item.name }}'
    organization: Default
    state: present
    inventory: '{{ awx_inventory_name }}'
    playbook: '{{ item.file }}'
    project: '{{ awx_project_name }}'
    credentials:
      - 'Host Credentials'
      - 'Vault Credentials'
    controller_host: '{{ controller_hostname }}'
    controller_username: '{{ controller_username }}'
    controller_password: '{{ controller_password }}'
    validate_certs: false
  loop:
    - {
        name: 'Proxmox - OMV Deployment',
        file: ansible/playbooks/vms/omv.yaml,
        enable_survey: false,
      }
    - {
        name: 'Proxmox - Docker Deployment',
        file: ansible/playbooks/vms/docker.yaml,
        enable_survey: false,
      }
