---
- name: Create a Job Template with Survey
  ansible.controller.job_template:
    name: '{{ item.name }}'
    organization: Default
    state: present
    inventory: '{{ awx_inventory_name }}'
    playbook: '{{ item.file }}'
    project: '{{ awx_project_name }}'
    credentials:
      - 'Host Credentials'
      - 'Vault Credentials'
    controller_host: '{{ controller_hostname }}'
    controller_username: '{{ controller_username }}'
    controller_password: '{{ controller_password }}'
    validate_certs: false
    survey_enabled: '{{ item.enable_survey }}'
    survey_spec: "{{ lookup('file', '{{item.survey_file}}') }}"
  loop:
    - {
        name: 'OpenShift - Prepare Cluster for Installation',
        file: ansible/playbooks/openshift/cluster-prep.yaml,
        enable_survey: true,
        survey_file: '../surveys/cluster-prep.json',
      }
    - {
        name: 'OpenShift - GitOps Bootstrap',
        file: ansible/playbooks/openshift/gitops-bootstrap.yaml,
        enable_survey: true,
        survey_file: '../surveys/gitops-bootstrap.json',
      }
    - {
        name: 'VMWare - Provision VM from Template',
        file: ansible/playbooks/vmware/provision-vm.yaml,
        enable_survey: true,
        survey_file: '../surveys/provision-vm.json',
      }
