---
- name: create vm Playbook
  hosts: localhost
  become: false
  gather_facts: false
  vars_files:
    - ../../vars/common.vault.yaml
  tasks:
    - name: create folder
      community.vmware.vcenter_folder:
        hostname: '{{ vcenter.hostname }}'
        username: '{{ vcenter.admin_username }}'
        password: '{{ vcenter.admin_password }}'
        validate_certs: 'false'
        datacenter_name: 'homelab'
        folder_name: 'rhel9_vms'
        folder_type: vm
        state: present

    - name: create VM
      vars:
        vm_name: testvm
      community.vmware.vmware_guest:
        hostname: '{{ vcenter.hostname }}'
        username: '{{ vcenter.admin_username }}'
        password: '{{ vcenter.admin_password }}'
        validate_certs: 'false'
        datacenter: 'homelab'
        name: '{{vm_name}}'
        folder: 'rhel9_vms'
        state: 'poweredoff'
        template: 'RHEL9_Template'
        cluster: 'cluster1'
        disk:
          - size_gb: '18'
            type: 'thin'
            datastore: 'datastore1'
        hardware:
          memory_mb: '4096'
          num_cpus: '2'
          scsi: 'paravirtual'
        networks:
          - name: 'VM Network'
            device_name: 'vmxnet3'
        advanced_settings:
          - key: 'guestinfo.metadata'
            value: "{{ lookup('ansible.builtin.template', '../../templates/meta-data.j2') | b64encode }}"
          - key: 'guestinfo.metadata.encoding'
            value: 'base64'
          - key: 'guestinfo.userdata'
            value: "{{ lookup('ansible.builtin.template', '../../templates/meta-data.j2') | b64encode }}"
          - key: 'guestinfo.userdata.encoding'
            value: 'base64'
      register: deploy_vm

    - ansible.builtin.debug: msg={{deploy_vm}}
