---
- name: create vm Playbook
  hosts: localhost
  become: false
  gather_facts: false
  vars_files:
    - ../../vars/common.vault.yaml
  environment:
    VMWARE_HOST: '{{ vcenter.hostname }}'
    VMWARE_USER: '{{ vcenter.admin_username }}'
    VMWARE_PASSWORD: '{{ vcenter.admin_password }}'
    VMWARE_VALIDATE_CERTS: 'false'
  tasks:
    - name: create folder
      community.vmware.vcenter_folder:
        datacenter_name: 'homelab'
        folder_name: 'rhel9_vms'
        folder_type: vm
        state: present

    - name: create VM
      vars:
        vm_name: testvm
      community.vmware.vmware_guest:
        datacenter: 'homelab'
        name: '{{vm_name}}'
        folder: 'rhel9_vms'
        state: 'poweredoff'
        template: 'RHEL9_Template'
        cluster: 'cluster1'
        disk:
          - size_gb: '18'
            type: 'thin'
            datastore: 'datastore1'
        hardware:
          memory_mb: '4096'
          num_cpus: '2'
          scsi: 'paravirtual'
        networks:
          - name: VM Network
            device_type: vmxnet3
            start_connected: true
            connected: true
      register: create_vm

    - name: configure VM
      vars:
        vm_name: testvm
      community.vmware.vmware_guest:
        name: '{{vm_name}}'
        advanced_settings:
          - key: 'guestinfo.metadata'
            value: "{{ lookup('ansible.builtin.template', '../../templates/meta-data.j2') | b64encode }}"
          - key: 'guestinfo.metadata.encoding'
            value: 'base64'
          - key: 'guestinfo.userdata'
            value: "{{ lookup('ansible.builtin.template', '../../templates/user-data.j2') | b64encode }}"
          - key: 'guestinfo.userdata.encoding'
            value: 'base64'
      register: configure_vm

    - name: Start VM
      vars:
        vm_name: testvm
      community.vmware.vmware_guest:
        name: '{{vm_name}}'
        state: poweredon
        wait_for_ip_address: true
