---
collections:
  - name: ansible.posix
  - name: ansible.utils
  - name: community.general
  - name: community.sops
  - name: kubernetes.core
  - name: ansible.controller
  - name: ansible.platform
  - name: ansible.hub
  - name: infra.controller_configuration
  - name: infra.aap_utilities
  - name: community.vmware
  - name: redhat.satellite
  - name: community.docker
roles:
  - src: https://github.com/geerlingguy/ansible-role-docker.git
    scm: git
    version: master
  - src: https://github.com/geerlingguy/ansible-role-pip.git
    scm: git
    version: master
