---
- name: Playbook to check if host is running and shutdown
  hosts: esxi.vikaspogu.internal
  become: true
  gather_facts: true
  ignore_unreachable: true
  vars_files:
    - ../../vars/common.vault.yaml
  tasks:
    - name: Ping database server with retries
      ansible.builtin.ping:
      register: ping_result

    - name: Shutdown host if its running
      community.general.shutdown:
      when:
        - ping_result.ping is defined and ping_result.ping == 'pong'
