---
proxmox:
  hosts:
    pxm-loki:
      ansible_user: root
    pxm-odin:
      ansible_user: root

omv:
  hosts:
    omv-odin.vikaspogu.internal:
      ansible_user: vikaspogu
    omv-loki.vikaspogu.internal:
      ansible_user: vikaspogu

swarm:
  children:
    swarm-master:
      hosts:
        swarm-odin.vikaspogu.internal:
          ansible_user: vikaspogu

    swarm-worker:
      hosts:
        swarm-loki.vikaspogu.internal:
          ansible_user: vikaspogu

aap:
  hosts:
    aap-controller:
      ansible_user: vikaspogu
