---
- name: Deploy VM on odin controller
  hosts: pxm-odin
  gather_facts: false
  vars_files:
    - ../../vars/common.vault.yaml
  tasks:
    - name: Import Proxmox Role
      ansible.builtin.include_role:
        name: ../../roles/proxmox
      vars:
        vm_name: aap-controller
        template_name: rhel-9-cloudinit-template
        mac_address: bc:24:11:a0:6e:7a
        cores: 8
        memory: 20480
        disk_size: 212G
        storage_name: nvme
        proxmox_hostname: 'pxm-odin'
        template_storage: synology-lun01

- name: Download and install AAP on the controller
  hosts: aap-controller
  gather_facts: false
  become: false
  tags: aap_installation
  roles:
    - infra.aap_utilities.aap_setup_download
    - infra.aap_utilities.aap_setup_prepare
    - infra.aap_utilities.aap_setup_install
  vars_files:
    - ../../vars/common.vault.yaml
  pre_tasks:
    - name: Wait 600 seconds for target connection to become reachable/usable
      ansible.builtin.wait_for_connection:
        delay: 5
        timeout: 600

    - name: Wait for cloud init to finish
      community.general.cloud_init_data_facts:
        filter: status
      register: res
      until: 'res.cloud_init_data_facts.status.v1.stage is defined and not res.cloud_init_data_facts.status.v1.stage'
      retries: 50
      delay: 5

    - name: Gathering facts
      setup:

    - name: Install required packages
      become: true
      ansible.builtin.dnf:
        name:
          - glibc-langpack-en
          - ansible-core
          - git
          - wget
          - unzip
          - tar
          - rsync
          - python3
          - python3-pip

    - name: Install boto and botocore python package
      become: true
      ansible.builtin.pip:
        name:
          - boto3
          - botocore
