---
- name: Delete a VM
  community.general.proxmox_kvm:
    node: '{{ proxmox_hostname }}'
    api_user: '{{ datacenter.username }}@pve'
    api_password: '{{ datacenter.password }}'
    api_host: '{{proxmox_hostname}}.{{domain_internal}}'
    name: '{{ vm_name }}'
    state: '{{ item }}'
  loop:
    - stopped
    - absent
