---
- name: Start a VM
  community.general.proxmox_kvm:
    node: '{{ proxmox_node }}'
    api_user: '{{ datacenter.username }}@pve'
    api_password: '{{ datacenter.password }}'
    api_host: '{{proxmox_hostname}}.{{domain_internal}}'
    name: '{{ vm_name }}'
    state: started
  delegate_to: localhost
