---
- name: create vm Playbook
  hosts: localhost
  become: false
  gather_facts: true
  vars_files:
    - ../../vars/common.vault.yaml
  environment:
    VMWARE_HOST: '{{ vcenter.hostname }}'
    VMWARE_USER: '{{ vcenter.admin_username }}'
    VMWARE_PASSWORD: '{{ vcenter.admin_password }}'
    VMWARE_VALIDATE_CERTS: 'false'
  tasks:
    - name: Provision VM
      ansible.builtin.include_role:
        name: ../../roles/provision-vm
      loop: '{{ vm_list }}'
      loop_control:
        loop_var: vm_list_data
      vars:
        vm_name: '{{ vm_list_data.name }}'
        vm_ip: '{{ vm_list_data.ip }}'
