---
- name: create vm Playbook
  hosts: localhost
  become: false
  gather_facts: false
  vars_files:
    - ../../vars/common.vault.yaml
  vars:
    vm_name: testvm
  environment:
    VMWARE_HOST: '{{ vcenter.hostname }}'
    VMWARE_USER: '{{ vcenter.admin_username }}'
    VMWARE_PASSWORD: '{{ vcenter.admin_password }}'
    VMWARE_VALIDATE_CERTS: 'false'
  tasks:
    - name: create folder
      community.vmware.vcenter_folder:
        datacenter_name: 'homelab'
        folder_name: 'rhel9_vms'
        folder_type: vm
        state: present

    - name: create VM
      community.vmware.vmware_guest:
        datacenter: 'homelab'
        name: '{{vm_name}}'
        folder: 'rhel9_vms'
        state: 'poweredoff'
        template: 'RHEL9_Template'
        cluster: 'cluster1'
        disk:
          - size_gb: '18'
            type: 'thin'
            datastore: 'datastore1'
        hardware:
          memory_mb: '4096'
          num_cpus: '2'
          scsi: 'paravirtual'

    - name: configure VM
      community.vmware.vmware_guest:
        name: '{{vm_name}}'
        advanced_settings:
          - key: 'guestinfo.metadata'
            value: "{{ lookup('ansible.builtin.template', '../../templates/meta-data.j2') | b64encode }}"
          - key: 'guestinfo.metadata.encoding'
            value: 'base64'
          - key: 'guestinfo.userdata'
            value: "{{ lookup('ansible.builtin.template', '../../templates/user-data.j2') | b64encode }}"
          - key: 'guestinfo.userdata.encoding'
            value: 'base64'

    - name: Start VM
      community.vmware.vmware_guest:
        name: '{{vm_name}}'
        state: poweredon
        wait_for_ip_address: true
      register: vm_details

    - ansible.builtin.debug:
        msg: '{{vm_details.instance.ipv4}}'

    # - name: Download katello rpm from satellite capsule
    #   ansible.builtin.dnf:
    #     name: "{{ item }}"
    #     state: present
    #     validate_certs: no
    #     disable_gpg_check: yes
    #   with_items:
    #     - url

    - name: Enable SELinux in enforcing mode
      ansible.posix.selinux:
        policy: targeted
        state: enforcing

    - name: Run the command module
      become: true
      ansible.builtin.command:
        cmd: '{{item}}'
      with_items:
        - fips-mode-setup --disable
        - update-crypto-policies --set DEFAULT:AD-SUPPORT
      delegate_to: '{{vm_details.instance.ipv4}}'

    - name: Install packages
      ansible.builtin.package:
        name:
          - common-tools
          - realmd
          - oddjob
          - oddjob-mkhomedir
          - sssd
          - adcli
          - krb5-workstation
          - authconfig
        state: present

    - name: Remove all wireless packages
      ansible.builtin.package:
        name: 'iwl*'
        state: absent
