---
- name: create vmdk template Playbook
  hosts: aap-controller
  become: true
  gather_facts: false
  vars_files:
    - ../../vars/common.vault.yaml
  environment:
    GOVC_URL: '{{ vcenter.hostname }}'
    GOVC_USERNAME: '{{ vcenter.admin_username }}'
    GOVC_PASSWORD: '{{ vcenter.admin_password }}'
    GOVC_INSECURE: 'false'
  tasks:
    - name: Creates directory
      ansible.builtin.file:
        path: '{{item}}'
        state: directory
      with_items:
        - /tmp/rhel-bootc-vmdk/image
        - /tmp/rhel-bootc-vmdk/output

    - name: Template a file for the Containerfile
      ansible.builtin.template:
        src: '../../templates/Containerfile.j2'
        dest: /tmp/rhel-bootc-vmdk/image/Containerfile

    - name: Run podman commands
      ansible.builtin.command:
        cmd: '{{item}}'
      args:
        chdir: /tmp/rhel-bootc-vmdk
      with_items:
        - podman build -f image/Containerfile -t localhost/rhel-bootc-vmdk image
        - podman run --rm -it --privileged -v /var/lib/containers/storage:/var/lib/containers/storage -v ./output:/output --security-opt label=type:unconfined_t --pull newer registry.redhat.io/rhel9/bootc-image-builder:9.4 --local --type vmdk localhost/rhel-bootc-vmdk:latest

    - name: Copy files from foo to bar
      ansible.builtin.copy:
        remote_src: true
        src: /tmp/rhel-bootc-vmdk/output/vmdk/disk.vmdk
        dest: /tmp/rhel-bootc-vmdk/output/vmdk/rhel-bootc-vmdk.vmdk

    - name: Run govc commands
      ansible.builtin.command:
        cmd: 'govc import.vmdk -dc="homelab" -ds="datastore1" output/vmdk/rhel-bootc-vmdk.vmdk vm-templates'
      args:
        chdir: /tmp/rhel-bootc-vmdk

    - name: Cleanup directory
      ansible.builtin.file:
        path: '/tmp/rhel-bootc-vmdk'
        state: absent
