---
- set_fact:
    crypto-policy: "{{ '{{crypto.rhel8}}' if ansible_distribution_version is version('8', '>=') else '{{crypto.rhel9}}' }}"

- name: Enable crypto policy allowing RC4 encryption
  ansible.builtin.command:
    cmd: update-crypto-policies --set '{{crypto-policy}}'
