---
- name: Run the command module
  ansible.builtin.command:
    cmd: subscription-manager identity
  register: subscription_result

- name: Register only when subscription identity is empty
  when: subscription_result.stdout.find('system identity') == -1
  block:
    - name: Download katello rpm from satellite capsule
      ansible.builtin.dnf:
        name: '{{ item }}/pub/katello-ca-consumer-latest.noarch.rpm'
        state: present
        validate_certs: no
        disable_gpg_check: yes
      with_items:
        - '{{satellite.url}}'

    - name: Register system and add subscription
      redhat.satellite.registration_command:
        username: '{{satellite.username}}'
        password: '{{satellite.password}}'
        activation_keys: '{{vm_vars.activation_keys}}'
        organization: '{{satellite.org}}'
        server_url: '{{satellite.url}}'
        validate_certs: false
      register: registration_result
      delegate_to: localhost
      become: false

    - name: Perform registration
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          {{ registration_result.registration_command }}
