---
- name: create VM
  community.vmware.vmware_guest:
    datacenter: 'homelab'
    name: '{{item.name}}'
    folder: ''
    state: 'poweredoff'
    template: 'RHEL9_Template'
    cluster: 'cluster1'
    disk:
      - size_gb: '18'
        type: 'thin'
        datastore: 'datastore1'
    hardware:
      memory_mb: '4096'
      num_cpus: '2'
      scsi: 'paravirtual'
    networks:
      ip: '{{item.ip}}'

- name: configure VM
  vars:
    vm_name: '{{ item.name }}'
  community.vmware.vmware_guest:
    name: '{{vm_name}}'
    advanced_settings:
      - key: 'guestinfo.metadata'
        value: "{{ lookup('ansible.builtin.template', 'meta-data.j2') | b64encode }}"
      - key: 'guestinfo.metadata.encoding'
        value: 'base64'
      - key: 'guestinfo.userdata'
        value: "{{ lookup('ansible.builtin.template', 'user-data.j2') | b64encode }}"
      - key: 'guestinfo.userdata.encoding'
        value: 'base64'

- name: Start VM
  community.vmware.vmware_guest:
    name: '{{vm_name}}'
    state: poweredon
    wait_for_ip_address: true
  register: vm_details
