---
- name: create VM
  community.vmware.vmware_guest:
    datacenter: 'homelab'
    name: '{{vm_name}}'
    folder: ''
    state: 'poweredoff'
    template: 'RHEL9_Template'
    cluster: 'cluster1'
    disk:
      - size_gb: '18'
        type: 'thin'
        datastore: 'datastore1'
    hardware:
      memory_mb: '4096'
      num_cpus: '2'
      scsi: 'paravirtual'
    networks:
      - name: VM Network
        ip: '{{vm_ip}}'
        netmask: 255.255.255.0
        gateway: 10.30.30.1
        mac: aa:bb:dd:aa:00:14

- name: configure VM
  community.vmware.vmware_guest:
    name: '{{vm_name}}'
    advanced_settings:
      - key: 'guestinfo.metadata'
        value: "{{ lookup('ansible.builtin.template', 'meta-data.j2') | b64encode }}"
      - key: 'guestinfo.metadata.encoding'
        value: 'base64'
      - key: 'guestinfo.userdata'
        value: "{{ lookup('ansible.builtin.template', 'user-data.j2') | b64encode }}"
      - key: 'guestinfo.userdata.encoding'
        value: 'base64'

- name: Start VM
  community.vmware.vmware_guest:
    name: '{{vm_name}}'
    state: poweredon
    wait_for_ip_address: true
  register: vm_details
