---
- hosts: localhost
  gather_facts: False
  vars_files:
    - ../../vars/common.vault.yaml
  environment:
    GOVC_USERNAME: '{{ vcenter.admin_username }}'
    GOVC_PASSWORD: '{{ vcenter.admin_password }}'
    GOVC_URL: 'https://{{ vcenter.ip }}'
    GOVC_DATACENTER: '{{ vcenter.datacenter }}'
    GOVC_INSECURE: 1
  roles:
    - vcenter_permissions
