---
- name: Playbook to delete a VM
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../../vars/common.vault.yaml
  tasks:
    - name: Delete a VM
      community.general.proxmox_kvm:
        node: '{{ proxmox_node }}'
        api_user: '{{ datacenter.username }}@pve'
        api_password: '{{ datacenter.password }}'
        api_host: '{{proxmox_hostname}}.{{domain_internal}}'
        name: '{{ vm_name }}'
        state: '{{ item }}'
      loop:
        - stopped
        - absent
